services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    networks:
      - frontend
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - backend
      - frontend
    ports:
      - "8000:8000"
    environment:
      - RUN_MIGRATIONS=true
      - DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    networks:
      - backend
#    ports:
#      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - backend
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  celery_worker:
    build: ./backend
    container_name: worker
    command: celery -A services.scrapper_service.celery_beat worker --loglevel=info --pool=solo
    networks:
      - backend
    environment:
      - BROKER_URL=redis://redis:6379/0
      - DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build: ./backend
    container_name: beat
    command: celery -A services.scrapper_service.celery_beat beat --loglevel=info
    networks:
      - backend
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
      - DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge