"""modify news and news source schemas

Revision ID: e53d9236e11a
Revises: f49d361388e9
Create Date: 2025-12-22 14:51:59.860560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53d9236e11a'
down_revision: Union[str, Sequence[str], None] = 'f49d361388e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('news_verification', sa.String(), server_default='not confirmed', nullable=False))
    op.create_unique_constraint(None, 'news_source', ['source_title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_source', type_='unique')
    op.drop_column('news', 'news_verification')
    # ### end Alembic commands ###
