"""create tables news_source, news_type

Revision ID: f49d361388e9
Revises: 157334040556
Create Date: 2025-12-22 10:54:12.990479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49d361388e9'
down_revision: Union[str, Sequence[str], None] = '157334040556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_source',
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('fake_news_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_type',
    sa.Column('news_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_type')
    )
    op.add_column('news', sa.Column('news_source_id', sa.Integer(), nullable=False))
    op.add_column('news', sa.Column('news_type_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_news_source_title'), 'news', type_='unique')
    op.create_unique_constraint('uq_news_source_title', 'news', ['news_source_id', 'title'])
    op.create_foreign_key(None, 'news', 'news_source', ['news_source_id'], ['id'])
    op.create_foreign_key(None, 'news', 'news_type', ['news_type_id'], ['id'])
    op.drop_column('news', 'source_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('source_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint('uq_news_source_title', 'news', type_='unique')
    op.create_unique_constraint(op.f('uq_news_source_title'), 'news', ['source_name', 'title'], postgresql_nulls_not_distinct=False)
    op.drop_column('news', 'news_type_id')
    op.drop_column('news', 'news_source_id')
    op.drop_table('news_type')
    op.drop_table('news_source')
    # ### end Alembic commands ###
