"""Update News by adding embeddings, importance, clustering

Revision ID: 140a8f032341
Revises: e53d9236e11a
Create Date: 2026-01-29 22:34:51.163581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "140a8f032341"
down_revision: Union[str, Sequence[str], None] = "e53d9236e11a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
    )
    op.add_column(
        "news",
        sa.Column("cluster_id", sa.Integer(), server_default="-1", nullable=False),
    )
    op.add_column(
        "news",
        sa.Column("importance_level", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news", "importance_level")
    op.drop_column("news", "cluster_id")
    op.drop_column("news", "embedding")
    # ### end Alembic commands ###
